#!/bin/bash

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
yellow='\033[1;33m'
cyan='\033[1;36m'
nocolor='\033[0m'

echo -e "${yellow}post-commit:${nocolor} don't forget the checkstyle!"
echo -e "${yellow}post-commit:${nocolor} run ${cyan}ng lint${nocolor} in the ${cyan}qtd-ng-frontend${nocolor} directory"
echo -e "${yellow}post-commit:${nocolor} run ${cyan}npx standard${nocolor} in the ${cyan}qtd-node-backend${nocolor} directory"
exit 0