version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  qtd-frontend: # name of the first service
    build: qtd-ng-frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    # volumes:
    #   - ./qtd-ng-frontend:/app

  qtd-backend: #name of the second service
    build: qtd-node-backend # specify the directory of the Dockerfile
    ports:
      - "4201:4201" #specify ports forewarding
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:3.6
