version: '2'

# Define the services/containers to be run
services:
  api-gateway:
    image: express-gateway
    ports: # ports forwarding
      - "8080:8080"
    volumes: # the right directory is /var/lib/eg/
      - ./qtd-express-gateway/config/gateway.config.yml:/var/lib/eg/gateway.config.yml

  qtd-frontend: # name of the service
    container_name: qtd-frontend
    build: qtd-ng-frontend # specify the directory of the Dockerfile
    expose: # the port is not published to the host machine
      - "4200" 
    environment:
      NG_PORT: 4200 # default angular dev port
    volumes:        # avoids to rebuild every time something changes
       - ./qtd-ng-frontend:/app

  qtd-backend:
    container_name: qtd-backend
    build: qtd-node-backend 
    expose:
      - "4201"
    environment: 
      API_PORT : 4201
      DB_HOST : mongo
      DB_PORT : 27017  # default mongodb port
    volumes: 
      - ./qtd-node-backend:/usr/src/app
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:3.6
