version: '2'

# Define the services/containers to be run
services:
  qtd-frontend: # name of the service
    build: qtd-ng-frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding
    volumes:        # avoids to rebuild every time something changes
       - ./qtd-ng-frontend:/app

  qtd-backend:
    build: qtd-node-backend 
    ports:
      - "4201:4201"
    environment: 
      API_PORT : 4201
      DB_HOST : mongo
      DB_PORT : 27017  # default mongodb port
    volumes: 
      - ./qtd-node-backend:/app
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:3.6
